---
- name: preparing system
  hosts: rhel
  gather_facts: no
  tasks:
#    - name: installing samba
 #     ansible.builtin.dnf:
  #      name: samba
   #     state: present
    
    - name: adding samba group
      ansible.builtin.group:
        gid: 5555
        name: sambaUser
        
    - name: adding default samba user
      ansible.builtin.user:
        append: true
        groups: sambaUser
        name: rex
        password: $6$TMqDx7nYtCrEYouM$lBL43M5167qbbkLxyCftNTNVwkSsb7MOdux5rotJwxXwAJ69v94WjbsAVz2.8QYXpcgN4UM71tMX6g0yFq.Zj/
        state: present
    
    - name: adding user to samba db
      ansible.builtin.command:  
        cmd: smbpasswd -a rex
        stdin: |
          password
          password

    - name: enabling sambauser
      command: smbpasswd -e rex

    - name: setting directory /srv/samba
      ansible.builtin.file:
        state: directory
        path: "/srv/samba"
        owner: root
        group: sambaUser
        mode: '0775'
        setype: samba_share_t

    - name: adding smb.conf.template
      ansible.builtin.copy:
        dest: /etc/samba/
        group: root
        mode: '0644'
        owner: root
        src: files/

    - name: starting samba server
      ansible.builtin.systemd_service:
        name: smb
        enabled: true
        state: started


